---
driver:
  name: terraform
  root_module_directory: test/fixtures
  parallelism: 4
  verify_version: false

provisioner:
  name: terraform

platforms:
  - name: gcp

suites:
  - name: single-project
    driver:
      root_module_directory: test/fixtures/single-project
  - name: organization
    driver:
      root_module_directory: test/fixtures/organization
  - name: single-project-k8s
    driver:
      root_module_directory: test/fixtures/single-project-k8s
